# Generated by Django 5.2 on 2025-05-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.TextField()),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('publication_year', models.TextField()),
                ('publisher', models.TextField()),
                ('image_s', models.TextField()),
                ('image_m', models.TextField()),
                ('image_l', models.TextField()),
            ],
        ),
    ]
