# Generated by Django 5.2 on 2025-05-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_userage_user_id_alter_userlocation_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userage',
            old_name='user_id',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='userlocation',
            old_name='user_id',
            new_name='id_user',
        ),
    ]
