# Generated by Django 5.2 on 2025-05-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_user_id_userage_id_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userage',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userlocation',
            old_name='id_user',
            new_name='user',
        ),
    ]
