# Generated by Django 5.2 on 2025-05-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_id_user_userage_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='location',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='region',
            field=models.TextField(null=True),
        ),
    ]
