# Generated by Django 5.2 on 2025-05-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_bookmodel_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.TextField()),
                ('title', models.TextField(null=True)),
                ('author', models.TextField(null=True)),
                ('publication_year', models.TextField(null=True)),
                ('publisher', models.TextField(null=True)),
                ('image_s', models.TextField(null=True)),
                ('image_m', models.TextField(null=True)),
                ('image_l', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BookModel',
        ),
    ]
