# Generated by Django 5.2 on 2025-05-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_userratingexplicit_userratingimplicit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userratingimplicit',
            name='rating',
        ),
    ]
