# Generated by Django 5.2 on 2025-05-02 19:13

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0017_usercomment_delete_usercomment1'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vector', pgvector.django.vector.VectorField()),
            ],
        ),
    ]
