# Generated by Django 5.2 on 2025-05-03 12:27

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_usercontentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontentprofile',
            name='vector',
            field=pgvector.django.vector.VectorField(null=True),
        ),
    ]
