# Generated by Django 5.2 on 2025-05-03 16:35

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_usercontentprofile_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookContentProfile',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.book')),
                ('vector', pgvector.django.vector.VectorField(null=True)),
            ],
        ),
    ]
