# Generated by Django 5.2 on 2025-05-04 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_bookcontentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='base.book')),
                ('similar_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='base.book')),
            ],
            options={
                'indexes': [models.Index(fields=['book'], name='base_booksi_book_id_db8f85_idx'), models.Index(fields=['similar_book'], name='base_booksi_similar_4f56cf_idx')],
                'unique_together': {('book', 'similar_book')},
            },
        ),
    ]
