# Generated by Django 5.2 on 2025-05-04 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_booksimilarity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('similar_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='base_usersi_user_id_35ee79_idx'), models.Index(fields=['similar_user'], name='base_usersi_similar_2d88c2_idx')],
                'unique_together': {('user', 'similar_user')},
            },
        ),
    ]
