# Generated by Django 5.2 on 2025-05-04 15:38

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_usersimilarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('bias', models.FloatField()),
                ('factors', pgvector.django.vector.VectorField(dimensions=20)),
                ('implicit', pgvector.django.vector.VectorField(dimensions=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('bias', models.FloatField()),
                ('factors', pgvector.django.vector.VectorField(dimensions=20)),
            ],
        ),
    ]
