# Generated by Django 5.2 on 2025-05-04 19:19

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_bookfactors_userfactors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfactors',
            name='factors',
            field=pgvector.django.vector.VectorField(dimensions=40),
        ),
        migrations.AlterField(
            model_name='bookfactors',
            name='implicit',
            field=pgvector.django.vector.VectorField(dimensions=40),
        ),
        migrations.AlterField(
            model_name='userfactors',
            name='factors',
            field=pgvector.django.vector.VectorField(dimensions=40),
        ),
    ]
